Final Project Comission App/hobbysite/blog/urls.py
from django.urls import path

from .views import BlogListView, BlogDetailView


urlpatterns = [
    path('articles', BlogListView.as_view(), name='list'),
    path('article/<int:pk>', BlogDetailView.as_view(), name='blog-detail')
]
app_name = 'blog'

Final Project Comission App/hobbysite/commissions/urls.py
from django.urls import path

from .views import CommissionListView, CommissionDetailView, CommissionCreateView, CommissionUpdateView


urlpatterns = [
    path('list', CommissionListView.as_view(), name='commission-list'),
    path('detail/<int:pk>', CommissionDetailView.as_view(), name='commission-detail'),
    path('add', CommissionCreateView.as_view(), name='commission-create'),
    path('<int:pk>/edit', CommissionUpdateView.as_view(), name='commission-update'),
]
app_name = 'commissions'

Final Project Comission App/hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('merchstore/', include('merchstore.urls', namespace="merchstores")),
    path('wiki/', include('wiki.urls', namespace = 'wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('commissions/', include('commissions.urls', namespace="commissions")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('user_management.urls', namespace="user_management")),
    path('homepage/', include('homepage.urls', namespace="homepage")),
]

Final Project Comission App/hobbysite/homepage/urls.py
from django.urls import path

from .views import HomepageView


urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
]
app_name = 'homepage'

Final Project Comission App/hobbysite/user_management/urls.py
from django.urls import path

from .views import ProfileUpdateView, DashboardView, UserCreateView, ProfileCreateView


urlpatterns = [
    path('', ProfileUpdateView.as_view(), name='profile-update'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('user/create', UserCreateView.as_view(), name='user-create'),
    path('profile/create', ProfileCreateView.as_view(), name='profile-create'),
    
]
app_name = 'user_management'

Final Project Comission App/hobbysite/commissions/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Commission(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    author = models.ForeignKey('user_management.Profile', on_delete=models.SET_NULL, null=True, related_name='commissions')
    openManpower = models.PositiveIntegerField(default=0)

    AOPEN = "AO"
    BFULL = "BF"
    CCOMPLETED = "CC"
    DDISCONTINUED = "DD"
    STATUS_CHOICES = {
        AOPEN: "Open",
        BFULL: "Full",
        CCOMPLETED: "Completed",
        DDISCONTINUED: "Discontinued",
    }
    status = models.CharField(max_length=13,choices=STATUS_CHOICES,default=AOPEN,)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('commissions:commission-detail', args=[self.pk])

    class Meta:
        ordering = ['created_at']
        verbose_name = 'Commission'
        verbose_name_plural = 'Commissions'


class Job(models.Model):
    commission = models.ForeignKey('Commission', on_delete=models.CASCADE, related_name='jobs')
    role = models.CharField(max_length=255)
    manpowerRequired = models.PositiveIntegerField()
    openManpower = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.openManpower = self.manpowerRequired
        super().save(*args, **kwargs)

    OPEN = "OPEN"
    FULL = "FULL"
    STATUS_CHOICES = {
        OPEN: "Open",
        FULL: "Full",
    }
    status = models.CharField(max_length=4,choices=STATUS_CHOICES,default=OPEN,)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
           return self.role

    class Meta:
        ordering = ["-status", "-manpowerRequired", "role"]
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'


class JobApplication(models.Model):
    job = models.ForeignKey('Job', on_delete=models.CASCADE, related_name='jobApplications')
    applicant = models.ForeignKey('user_management.Profile', on_delete=models.CASCADE, related_name='jobApplications')

    APENDING = "AP"
    BACCEPTED = "BP"
    CREJECTED = "CR"
    STATUS_CHOICES = {
        APENDING: "Pending",
        BACCEPTED: "Accepted",
        CREJECTED: "Rejected",
    }

    status = models.CharField(max_length=9,choices=STATUS_CHOICES,default=APENDING,)

    applied_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["status", "-applied_at"]
        verbose_name = 'Job Application'
        verbose_name_plural = 'Job Applications'


@receiver(post_save, sender=JobApplication)
def update_job_manpower(sender, instance, created, **kwargs):
    if instance.status == JobApplication.BACCEPTED:
        instance.job.openManpower -= 1
        if instance.job.openManpower == 0:
            instance.job.status = Job.FULL
        instance.job.save()


@receiver(post_save, sender=Job)
def update_commission_manpower(sender, instance, created, **kwargs):
    commission = instance.commission
    jobs = Job.objects.filter(commission=commission)
    commission.openManpower = sum(job.openManpower for job in jobs)
    if commission.openManpower == 0:
        commission.status = Commission.BFULL
    commission.save()

Final Project Comission App/hobbysite/homepage/models.py
from django.db import models

# Create your models here.

Final Project Comission App/hobbysite/homepage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class HomepageView(TemplateView):
    template_name = 'homepage.html'

Final Project Comission App/hobbysite/templates/base.html
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css">
    <title>{% block title %}Hobby Site{% endblock %}</title>
    {% block styles %}{% endblock %}
</head>
<body>
    <table width="100%" height="40px" border="1">

        <td width="16%" align="center"><b>Navigation Bar:</b></td>

        <td width="16%" align="center"><b><a href="{% url 'homepage:homepage' %}">
        Homepage</a></b></td>

        <td width="16%" align="center"><b><a href="{% url 'commissions:commission-list' %}">
        Merchstore Items</a></b></td>

        <td width="16%" align="center"><b><a href="{% url 'commissions:commission-list' %}">
        Wiki Articles</a></b></td>

        <td width="16%" align="center"><b><a href="{% url 'commissions:commission-list' %}">
        Blog Articles</a></b></td>

        <td width="16%" align="center"><a href="{% url 'commissions:commission-list' %}">
        <b>Commissions</a></b></td>

    </table>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
</body>
</html>

Final Project Comission App/hobbysite/templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog Detail{% endblock %}
{% block content %}
    <body>
        <h1>Blog Detail - {{ object.category.name }}</h1>
        <p>{{ object.entry }}</p>
    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog List{% endblock %}
{% block content %}
    <body>
        <h1>Blog:</h1>
        {% for b in object_list %}
            <h2>
            <li>
                <a href="{{ b.get_absolute_url }}">
                    {{ b }}
                </a>
            </li>
            </h2>
        {% endfor %}
    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/commissions_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Commission Create{% endblock %}
{% block content %}
    <body>
        <form method="POST">
        <h2>Create a Commission: </h2>
            {% csrf_token %}
            {{ form.as_div }}
        <h2>Jobs for this Commission (Leave Blank If Not Needed):</h2>
            {{ job_formset.management_form }}
            {% for job_form in job_formset %}
            <h3>Create Job: </h3>
                {{ job_form.as_div }}
            {% endfor %}
            <button>Submit</button>
        </form>
    </body>
</html>
{% endblock %}

Final Project Comission App/hobbysite/templates/commissions_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Commission Detail{% endblock %}
{% block content %}
    <body>
        <h1>{{ object.title }} Commission</p></h1>
        <h3>Author - {{ object.author }}</h3>
        <h3>Status - {{ object.get_status_display }}</h3>
        <p><strong>Commission Description: </strong> {{ object.description}}</p>
        <p><strong>Created On:</strong> {{ object.created_at}}</p>
        <p><strong>Last Updated:</strong> {{ object.updated_at}}</p>
        <p><strong>Total Manpower Required for Commission: </strong>{{ total_manpower }}</p>
        <p><strong>Open Manpower for Commission: </strong>{{ object.openManpower }}</p>
        &nbsp;
        <h2>List of Jobs Needed:</h2>
        {% for job in object.jobs.all %}
            <h3><p>{{ job }}</p></h3>
            <li>Total Manpower Needed:  {{ job.manpowerRequired }}</li>
            <li>Open Manpower:  {{ job.openManpower }}</li>
        {% endfor %}
        {% if request.user.is_authenticated %}
        <h2>Application Form:</h2>
        <p><strong>Current User: </strong> {{ user.profile }}</p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <button>Apply to Job</button>
        </form>
        {% endif %}
        {% if request.user.is_authenticated and request.user.profile == object.author %}
            <h2><a href="{% url 'commissions:commission-update' object.pk %}">Edit This Commission</a></h2>
        {% endif %}
    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/commissions_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Commission List{% endblock %}
{% block content %}
    <body>
        <h1>Commissions:</h1>
        {% for c in object_list %}
            <h4>
            <li>
                <a href="{{ c.get_absolute_url }}">
                    {{ c }}
                </a>
                - {{ c.get_status_display }}
            </li>
            </h4>
        {% endfor %}

        {% if request.user.is_authenticated %}
            <h2>Current User: {{ user.profile }}</h2>
            <h2>Created Commissions:</h2>
            {% for d in user.profile.commissions.all %}
                <h4>
                <li>
                    <a href="{{ d.get_absolute_url }}">
                        {{ d }}
                    </a>
                    - {{ d.get_status_display }}
                </li>
                </h4>
            {% endfor %}

            <h2>Applied Commissions:</h2>
            {% for e in user.profile.jobApplications.all %}
                <h4>
                <li>
                    <a href="{{ e.job.commission.get_absolute_url }}">
                        {{ e.job.commission }}
                    </a>
                    - {{ e.get_status_display }}
                </li>
                </h4>
            {% endfor %}
        {% else %}
        {% endif %} 

        <h2>
            <a href="{% url 'commissions:commission-create' %}">
                Make a New Commission
            </a>
        </h2>
    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/commissions_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Update Commission{% endblock %}
{% block content %}
    <body>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <button>Submit</button>
        </form>
    </body>
</html>
{% endblock %}

Final Project Comission App/hobbysite/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <body>
        <h1>Dashboard - {{ object }}</h1>
    
        <h3>List of Products Bought: </h3>

        <h3>List of Products Sold: </h3>

        <h3>List of Wiki Articles Created: </h3>

        <h3>List of Blog Articles Created: </h3>

        <h3>List of Threads Created: </h3>

        <h3>List of Commissions Created: </h3>
        {% for cc in object.commissions.all %}
            <h4>
            <li>
                <a href="{{ cc.get_absolute_url }}">
                    {{ cc }}
                </a>
            </li>
            </h4>
        {% endfor %}

        <h3>List of Commissions Joined: </h3>
        {% for cj in object.jobApplications.all %}
            <h4>
            <li>
                <a href="{{ cj.job.commission.get_absolute_url }}">
                    {{ cj.job.commission }}
                </a>
            </li>
            </h4>
        {% endfor %}

    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Homepage{% endblock %}
{% block content %}
    <body>
        <h1>Homepage</h1>
        <h2>Merchandise Store: </h2>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            List of Merchstore Items
        </a></li></h3>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            Add a Merchstore Item
        </a></li></h3>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            Merchstore Cart
        </a></li></h3>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            Merchstore Transactions List
        </a></li></h3>

        <h2>Online Wiki: </h2>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            List of Wiki Articles
        </a></li></h3>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            Add a Wiki Article
        </a></li></h3>

        <h2>Blog: </h2>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            List of Blog Articles
        </a></li></h3>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            Add a Blog Article
        </a></li></h3>

        <h2>Commission: </h2>

        <h3><li><a href="{% url 'commissions:commission-list' %}">
            List of Commissions
        </a></li></h3>

        <h3><li><a href="{% url 'commissions:commission-create' %}">
            Add a Commission
        </a></li></h3>

        <h2>User Management: </h2>

        <h3><li><a href="{% url 'user_management:dashboard' %}">
            Dashboard
        </a></li></h3>

        <h3><li><a href="{% url 'admin:index' %}">
            Admin
        </a></li></h3>

        <h3><li><a href="{% url 'login' %}">
            Login
        </a></li></h3>

        <h3><li><a href="{% url 'user_management:user-create' %}">
            Register a User
        </a></li></h3>

        <h3><li><a href="{% url 'user_management:profile-create' %}">
            Create a Profile
        </a></li></h3>


    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/merchstore_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Merchstore Items{% endblock %}
{% block content %}
    <body>
        <h1>Items:</h1>
        {% for item in object_list %}
            <h2>
            <li>
                <a href="{{ item.get_absolute_url }}">
                    {{ item }}
                </a>
            </li>
            </h2>
        {% endfor %}
    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/user_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Create{% endblock %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <title>User Create</title>
    <head>
    <body>
        <p>{{ object }}</p>
        <form action="" method="POST">
            <h2>Create a User: </h2>
            {% csrf_token %}
            {{ form.as_div }}
            <button>Submit</button>
        </form>
    </body>
</html>
{% endblock %}

Final Project Comission App/hobbysite/templates/user_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>User Detail</title>
    <head>
    <body>
        <p>{{ object }}</p>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <button>Submit</button>
        </form>
    </body>
</html>

Final Project Comission App/hobbysite/templates/wiki_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Wiki Detail{% endblock %}
{% block content %}
    <body>
        <h1>Wiki Detail - {{ object.category.name }}</h1>
        <p>{{ object.entry }}</p>
    </body>
{% endblock %}

Final Project Comission App/hobbysite/templates/wiki_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Wiki List{% endblock %}
{% block content %}
    <body>
        <h1>Wiki:</h1>
        {% for c in object_list %}
            <h2>
            <li>
                <a href="{{ c.get_absolute_url }}">
                    {{ c }}
                </a>
            </li>
            </h2>
        {% endfor %}
    </body>
{% endblock %}